services:
  skab-pytorch:
    build: .
    image: dsdante/skab-pytorch
    ports:
      - 8000:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
